[supervisord]
nodaemon=true

[program:v2ray]
command=/opt/v2ray -config /etc/v2raya/v2ray.json
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:v2raya]
command=/opt/v2raya --host 0.0.0.0 --port 2017
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0