name: "v2rayA Official"
description: "基于 mzz2017/v2raya 官方镜像的 Home Assistant 加载项"
version: "2.2.5"
slug: "v2raya"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
# 开启宿主机网络模式，透明代理必选
host_network: true
# 开启 Ingress，支持从 HA 侧边栏直接访问
ingress: true
ingress_port: 2017
panel_icon: "mdi:alpha-v-box"
panel_title: "v2rayA"
# 给予网络管理权限，用于透明代理设置 iptables
privileged:
  - NET_ADMIN
map:
  - config:rw
options:
  log_level: "info"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
