name: "v2rayA for HA"
description: "A web GUI client of Project V with Ingress support."
version: "1.1.0"
slug: "v2raya"
arch:
  - aarch64
  - amd64
# 开启 Ingress 功能
ingress: true
ingress_port: 2017
panel_icon: "mdi:security-network"
panel_title: "v2rayA"
# 如果你需要透明代理，建议开启 host_network
host_network: true
map:
  - config:rw
options:
  log_level: "info"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
