name: "v2rayA for Home Assistant"
description: "A web GUI client of Project V which supports V2Ray, Xray, Trojan, Shadowsocks, etc."
version: "1.0.0"
slug: "v2raya"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  2017/tcp: 2017        # v2rayA 控制面板端口
  2017/udp: 2017
  1080/tcp: 1080        # SOCKS 代理端口（根据需要调整）
map:
  - config:rw           # 允许持久化存储配置
options:
  log_level: "info"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
